services:
  - type: web
    name: cs-manager-backend
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_PORT
        value: "3001"
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: REDIS_HOST
        value: ""
      - key: FRONTEND_URL
        sync: false
